CREATE TABLE IF NOT EXISTS MKT_DATA(
    MKT_SYMBOL     VARCHAR(250),
    MKT_DATE       DATE,
    MKT_OPEN       NUMERIC(16, 4),
    MKT_HIGH       NUMERIC(16, 4),
    MKT_LOW        NUMERIC(16, 4),
    MKT_CLOSE      NUMERIC(16, 4),
    MKT_VOLUME     BIGINT,
    UNIQUE(MKT_SYMBOL, MKT_DATE)
);